### ISSUE TITLE
Release the egg on PyPI

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.auditlog#8]
Why not? 
If you want I can do it after I fixed #7!
Just let me know the pypi user to add as mantainers.

**Comment by rain2o** [comment]
That's a great idea @ale-rt ! I never got around to doing it, and have since then been working in other platforms and haven't had the chance to get back to this one. You are more than welcome to go ahead and do that. You can add Joel Rainwater (rain2o) to it. 
Thanks!

**Comment by ale-rt** [comment]
I would like to merge #10 before releasing: it is basically a clean up with automatic tools.

Which version should we ship on PyPI?
I see that in the setup.py we have 1.1 and in docs/HISTORY.txt 1.0dev.

Is it good if I release directly 1.2.0?

**Comment by rain2o** [comment]
It looks setup.py and history got out of sync. Version 1.2.0 would make the most sense I believe. That sounds good to me.

**Comment by ale-rt** [comment]
I released it:

- https://pypi.python.org/pypi/collective.auditlog

Can you give me write acces to this repository?
Apparently I cannot push to this repo.
I you could check this, it would be great.

**Comment by ale-rt** [comment]
I forgot to say that I set rain2o as an owner of the pypi package:
![image](https://cloud.githubusercontent.com/assets/1300763/14982396/4773cdca-1136-11e6-8cea-4eb2d84c2aa6.png)

Maybe you want to check if this is working!

**Comment by rain2o** [comment]
Awesome, thanks for doing that! I tested it and everything looks good to me on pypi. 
Unfortunately I don't think I can actually give write access to you since the repo is now under the Collective group, and I'm just standard member. Unless I'm overlooking something. Maybe @vangheem can help with that.

**Comment by ale-rt** [comment]
It would be great, because I have to push the tag and this patch from my fork:

- https://github.com/ale-rt/collective.auditlog/commit/8f7105a00bd2b4c60fd364bceb906d57bac0f192

**Comment by ale-rt** [comment]
I also released 1.2.1 today
